version: 2

sphinx:
  # This should not fail on errors so that we can view the rendered Read The Docs
  # pages even on errors.
  # We have a separate build process which fails on errors and shows all
  # the errors in one go.
  # This can be re-enable once RTD is updated with
  # https://github.com/readthedocs/readthedocs.org/issues/7116
  fail_on_warning: false

python:
  os: ubuntu-22.04
  version: 3.11
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
