# Docs:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions



name: CI/CD

on: [push, pull_request]


jobs:

  info:

    name: Workflow information
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:

      - name: Print GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}";

      - name: Print Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "${JOB_CONTEXT}";

      - name: Print Steps Context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "${STEPS_CONTEXT}";

      - name: Print Runner Context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "${RUNNER_CONTEXT}";

      - name: Print Strategy Context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "${STRATEGY_CONTEXT}";

      - name: Print Matrix Context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "${MATRIX_CONTEXT}";


  flake8:

    name: Flake8 (linter)

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Tox
        run: pip install tox;

      - name: Run Flake8
        run: tox -e flake8;


  black:

    name: Black (linter)

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Tox
        run: pip install tox;

      - name: Run Black
        run: tox -e black;


  mypy:
    name: Mypy (static type checker)

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Tox
        run: pip install tox;

      - name: Run Mypy
        run: tox -e mypy;


  docs:

    name: Build documentation

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Tox
        run: pip install tox;

      - name: Build documentation
        run: tox -e docs;


  docs-linkcheck:

    name: Documentation link check

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Tox
        run: pip install tox;

      - name: Check for broken links in documentation
        run: tox -e docs-linkcheck;


  packaging:
    name: Packaging

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Tox
        run: pip install tox;

      - name: Check packaging
        run: tox -e packaging;


  unit:
    name: Unit Tests using Python ${{ matrix.python }} on Ubuntu with Twisted ${{ matrix.twisted }}

    needs: [flake8, black, mypy, docs, packaging]

    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "pypy3"]
        twisted: ["18.4", "19.2", "current"]

    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: pip install tox;

      - name: Run unit tests
        shell: bash
        run: |
          py="${{ matrix.python }}";
          if [ "${py#pypy}" != "${py}" ]; then  # PyPy
              py_test="${py}";
              py_codecov="${py}";
          else  # CPython
              py_test="py${py/./}";  # Add "py" prefix, remove "."
              py_codecov="py";
          fi;
          twisted="${{ matrix.twisted }}";
          twisted="tw${twisted/./}";  # Add "tw" prefix, remove "."
          env_test="coverage-${py_test}-${twisted}";
          env_codecov="codecov-${py_codecov}";
          envs="${env_test},${env_codecov}";
          echo "Test environments: ${envs}";
          tox -e "${envs}";
          ln -s ".tox/${env_test}" testenv;  # Fixed location for upload step below
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_COMMIT: ${{ github.sha }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_WORKFLOW: ${{ github.workflow }}

      - name: Upload Trial log artifact
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: trial
          path: testenv/log/trial.log
